nelmio_api_doc:
    documentation:
        info:
            title: Notes API
            description: This is an awesome notes app!
            version: 1.0.0
        securityDefinitions:
            bearer:
                type: apiKey
                name: Authorization
                in: header
    areas: # to filter documented routes
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
