version: "3"
services:
  db:
    image: mariadb:10.3
    environment:
      - MYSQL_PASSWORD=notes
      - MYSQL_USER=notes
      - MYSQL_DATABASE=notes
    ports:
      - "3306"
    networks:
      - internal

  adminer:
    image: adminer
    ports:
      - "8080"
    links:
      - db
    networks:
      - internal

  php:
    build: ./php
    expose:
      - "9000"
    links:
      - db
      - memcached
    volumes:
      - "./:/var/www/html:delegated"
    networks:
      - internal

  nginx:
    build: ./nginx
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST-localhost}
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=DDL-${VIRTUAL_HOST-localhost}'
      - 'traefik.frontend.rule=Host:${VIRTUAL_HOST-localhost}'
      - 'traefik.docker.network=humpback_proxy'
      - 'traefik.port=80'
    ports:
      - "80"
    links:
      - php
    volumes:
      - "./:/var/www/html:delegated"
    networks:
      - internal
      - humpback_proxy

  cli:
    build: ./cli
    links:
      - php
      - nginx
      - db
      - memcached
      - browser
    volumes:
      - "./:/var/www/html:delegated"
      - "~/.ssh:/.ssh:delegated"
    networks:
      - internal

  memcached:
    image: memcached:1-alpine
    environment:
      # Memcached memory limit in megabytes
      - MEMCACHED_MEMORY_LIMIT=128
    networks:
      - internal

  browser:
    image: selenium/standalone-chrome-debug:3.6.0
    # This helps keep selenium-chrome from crashing because it uses shared memory.
    volumes:
      - /dev/shm:/dev/shm
    links:
      - nginx
    ports:
      - "5900"
    networks:
      - internal

  share:
    image: fnichol/ngrok
    environment:
      - HTTP_PORT=nginx:80
    links:
      - nginx
    ports:
      - "4040"
    networks:
      - internal

  varnish:
    image: thiagofigueiro/varnish-alpine-docker:3.5
    environment:
      - VARNISH_BACKEND_ADDRESS=nginx
      - VARNISH_BACKEND_PORT=80
    links:
      - nginx
    ports:
      - "80"
    networks:
      - internal

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025"
      - "8025"
    networks:
      - internal
networks:
  humpback_proxy:
    external: true
  internal:
    external: false
